src/Alpaca/urls.py
from django.conf.urls import url

import views

app_name = "alpaca"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/group/$', views.group_index, name='group_index'),
    url(r'^index/event/$', views.event_index, name='event_index'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^terms_conditions/$', views.terms_conditions, name='terms_conditions'),

    url(r'^forgotpassword/$', views.forgot_password, name="forgot_password"),
    url(r'^resetpassword$', views.reset_password, name='reset_password'),

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate$', views.activate, name='activate'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^profile/(?P<username>\w+)$', views.profile, name='profile'),
    url(r'^editprofile$', views.edit_profile, name='edit_profile'),
    url(r'^changepassword/$', views.change_password, name="change_password"),

    url(r'^group/new/$', views.new_group, name='new_group'),
    url(r'^group/(?P<group_id>[0-9]+)$', views.group, name='group'),
    url(r'^group/(?P<group_id>[0-9]+)/edit/$', views.edit_group, name='edit_group'),
    url(r'^group/join/(?P<group_id>[0-9]+)$', views.join_group, name='join_group'),
    url(r'^group/leave/(?P<group_id>[0-9]+)$', views.leave_group, name='leave_group'),
    url(r'^group/action/(?P<group_id>[0-9]+)$', views.handle_member, name='handle_member'),
    url(r'^group/demote/(?P<group_id>[0-9]+)$', views.demote_admin, name='demote_admin'),
    url(r'^group/members/(?P<group_id>[0-9]+)$', views.group_pending_members, name='group_pending_members'),
    url(r'^group/activities/(?P<group_id>[0-9]+)$', views.group_pending_activities, name='group_pending_activities'),

    url(r'^activity/new/$', views.new_activity, name='new_activity'),
    url(r'^activity/(?P<activity_id>[0-9]+)$', views.activity, name='activity'),
    url(r'^activity/(?P<activity_id>[0-9]+)/edit/$', views.edit_activity, name='edit_activity'),
    url(r'^activity/join/(?P<activity_id>[0-9]+)$', views.join_activity, name='join_activity'),
    url(r'^activity/leave/(?P<activity_id>[0-9]+)$', views.leave_activity, name='leave_activity'),
    url(r'^activity/kick/(?P<activity_id>[0-9]+)$', views.activity_kick_attendant, name='activity_kick_attendant'),
    url(r'^activity/pending/(?P<activity_id>[0-9]+)$', views.activity_pending_requests, name='activity_pending_attendants'),

    url(r'^activity/(?P<activity_id>[0-9]+)/new/$', views.new_session, name='new_session'),
    url(r'^activity/(?P<activity_id>[0-9]+)/edit/(?P<session_id>[0-9]+)$', views.edit_session, name='edit_session'),
    url(r'^activity/(?P<activity_id>[0-9]+)/confirm/$', views.confirm_session, name='confirm_session'),

    url(r'^event/new/(?P<group_id>[0-9]+)$', views.new_event, name='new_event'),
    url(r'^event/(?P<event_id>[0-9]+)$', views.event, name='event'),
    url(r'^event/(?P<event_id>[0-9]+)/edit/$', views.edit_event, name='edit_event'),
    url(r'^event/join/(?P<event_id>[0-9]+)$', views.join_event, name='join_event'),
    url(r'^event/leave/(?P<event_id>[0-9]+)$', views.leave_event, name='leave_event'),
    url(r'^event/kick/(?P<event_id>[0-9]+)$', views.event_kick_attendant, name='event_kick_attendant'),
    url(r'^event/attendants/(?P<event_id>[0-9]+)$', views.event_pending_attendants, name='event_pending_attendants'),
    url(r'^event/activities/(?P<event_id>[0-9]+)$', views.event_pending_activities, name='event_pending_activities'),
    url(r'^event/(?P<event_id>[0-9]+)/activity/new/$', views.event_new_activity, name='event_new_activity'),
]

src/WarLlama/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('Alpaca.urls')) ## Enabling translation
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

## About Multi-Language, quoting: 
## http://stackoverflow.com/questions/10280881/django-site-with-2-languages/26520044#26520044
# Wrap your text with lazytext! import lazytext (as above) and wrap every string 
# with it like so _('text'), you can even go to your other urls.py files and do url 
# translation like so:
#
# >>> url(_(r'^dual_language/$'), landing, name='duallang_landing'), <<<
#
# You can wrap text that you want translated in your other files, such as models.py, 
# views.py etc.. Here is an example model field with translations for label and help_text:
#
# >>> name = models.CharField(_('name'), max_length=255, unique=True, help_text=_("Name of the FAQ Topic")) <<<
#
# Django translation docs are great for this!

src/Alpaca/views/activity.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from django.views.generic import *
from django.core.urlresolvers import reverse

from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils.translation import ugettext_lazy as _ ## For Multi-Language

from itertools import chain

from ..models import Activity, Session
from ..forms import ActivityForm
from ..utils import set_translation, handle_form

import datetime


## -- ACTIVITIES -- ##
def activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user
    session_list = activity.session_set.order_by('start_date')
    context = { 'user': user,
                'activity': activity,
                'session_list': session_list}




    if user.is_authenticated:
        context['user_has_actions'] = True

        if activity.pending_event != None:
            context['user_has_actions'] = False
            context['why_not_message'] = _("This activity is waiting to be part of an event! Come back later :)")        

        elif activity.event != None and not activity.event.is_user_attending(user):
            context['user_has_actions'] = False
            context['why_not_message'] = _("This activity is part of an event. Join the event to attend this activity!")        
            
        elif not activity.is_user_old_enough(user):
            context['user_has_actions'] = False
            context['why_not_message'] = _("You are too young to attend this activity.")

        elif user in activity.pending_attendants.all():
            context['user_has_actions'] = False
            context['why_not_message'] = _("The author of this activity has received your request to join!") 

        if user == activity.author:
            return render(request, 'Alpaca/activity/activity_author.html', context)
        else:
            return render(request, 'Alpaca/activity/activity_user.html', context)
    else:        
        return render(request, 'Alpaca/activity/activity_anon.html', context)

@login_required
def new_activity(request):
    set_translation(request)    
    user = request.user    

    context = { 'form_title': _("Start a new activity"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }

    user_groups = user.profile.get_groups()

    if request.method == "POST":
        form = ActivityForm(user_groups, request.POST, request.FILES )
        if form.is_valid():
           activity = form.save_new(user)        
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForm(group_list=user_groups) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def edit_activity(request, activity_id):
    set_translation(request)
    user = request.user
    activity = get_object_or_404(Activity, pk=activity_id)
    if user != activity.author:
        return  HttpResponseRedirect(reverse('alpaca:index'))
 
    if activity.group != None or activity.pending_group != None:
        user_groups = [activity.group.id]
    else:
        user_groups = user.profile.get_groups()
    
    context = { 'form_title': _("Editing activity") + " " + activity.title,
                'submit_text': _("Save changes"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = ActivityForm(user_groups, request.POST, request.FILES, instance=activity)
        if form.is_valid():
           activity = form.save()   
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForm(group_list=user_groups, instance=activity) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def join_activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user

    if request.method == "POST":
        activity.join(user)

    return HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def leave_activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user

    if request.method == "POST":
        activity.leave(user)

    return HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def activity_kick_attendant(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("attending"))
        activity.kick(selected_user)

    return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def activity_pending_requests(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("user_join_request"))
        activity.handle_user_request(selected_user, "accept_request" in request.POST)

    return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))

src/Alpaca/views/event.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from django.views.generic import *
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils import timezone
from django.utils.translation import ugettext_lazy as _ ## For Multi-Language

from ..models import Profile, Group, Event, Activity
from ..forms import EventForm, ActivityForEventForm
from ..emails import email_reset_password

from ..utils import set_translation, sort_activities

import datetime


def event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    to_sort_column = request.GET.get('order_by')
    sorted_column = request.GET.get('last')
    context = sort_activities(Activity.objects.filter(event_id=event.id), to_sort_column, sorted_column)

    context['user'] = request.user
    context['event'] = event

    if user.is_authenticated:
        context['user_is_old_enough'] = event.is_user_old_enough(user)
        if user == event.group.superuser or user in event.group.admin_list.all():
            return render(request, 'Alpaca/event/event_admin.html', context)
        else:
            return render(request, 'Alpaca/event/event_user.html', context)
    else:        
        return render(request, 'Alpaca/event/event_anon.html', context)

@login_required
def new_event(request, group_id):
    set_translation(request)
    
    user = request.user
    group = get_object_or_404(Group, pk=group_id)

    if user != group.superuser and user not in group.admin_list.all():
        return  HttpResponseRedirect(reverse('alpaca:index'))
    

    context = { 'form_title': _("Start a new event!"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save_new(group)                     
            return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event.id}))
        else:
            context['form'] = form
            return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)

    else:
        context['form'] = EventForm() 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def edit_event(request, event_id):
    set_translation(request)
    user = request.user
    event = get_object_or_404(Event, pk=event_id)
    
    if user != event.group.superuser and user not in event.group.admin_list.all():
        return  HttpResponseRedirect(reverse('alpaca:index'))

    context = { 'form_title': _("Editing event") + " " + event.title,
                'submit_text': _("Save changes"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            event = form.save()
            return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event.id}))
        else:
            context['form'] = form
            return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)

    else:
        context['form'] = EventForm(instance=event)
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


## USER ACTIONS ##
@login_required
def join_event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    if request.method == "POST":
        event.join(user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def leave_event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    if request.method == "POST":
        event.leave(user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))

@login_required
def event_new_activity(request, event_id):
    user = request.user
    event = get_object_or_404(Event, pk=event_id)

    if not event.is_user_attending(user):
        return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))
    
    context = { 'form_title': _("Start a new activity"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }
    
    if request.method == "POST":
        form = ActivityForEventForm(event.group, event, request.POST, request.FILES )
        if form.is_valid():
           activity = form.save_new(user)        
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForEventForm(group=event.group, event=event) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    


## ADMIN ACTIONS ##
@login_required
def event_kick_attendant(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("attending"))
        event.kick(selected_user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def event_pending_attendants(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("user_join_request"))
        event.handle_user_request(selected_user, "accept_request" in request.POST)

    return HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def event_pending_activities(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_activity = get_object_or_404(Activity, id=request.POST.get("activity_request"))
        event.handle_activity_request(selected_activity, "accept_request" in request.POST)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))

src/Alpaca/templates/Alpaca/shared/visuals/_activity-card.html
{% load i18n %}


<a class="al-card"href="/activity/{{activity.id}}">
    {% if not activity.cover or activity.cover.name != "False" %}
        <div class="al-card-cover" style="background-image: url({{activity.cover.url}});">  
        </div>
    {% endif %}
    <div class="al-card-body">
        <div class="al-card-header">
            <h1>{{ activity.title }} <span class="al-text-tail">{% trans "by" %} {{ activity.author }}</span></h1>
            <div class="al-card-descriptors">             
                {% with activity.get_next_session as next_session %}
                    {% if next_session %}
                        <span class="next-session"><i class="fa fa-calendar-check-o"></i> {{ next_session.start_date }}</span>
                    {% else %}
                        <span class="no-sessions"><i class="fa fa-calendar-times-o"></i> {% trans "No future sessions planned" %}</span>
                    {% endif %}
                {% endwith %}
                <span class="at-descriptor"><i class="fa fa-map-marker"></i> {{ activity.city }}</span>
                <span class="attendant-count"><i class="fa fa-user"></i> {{ activity.attendants.count }}</span>
                
                {% if activity.age_minimum >= 18 %}
                    <span class="adults-only">+18</span>
                {% endif %}
            </div>
        </div>

        <div class="al-card-text">
            {{ activity.get_short_description | safe }}
        </div>
        
        <div class="al-card-footer">
            <span class="al-card-pub-date"><i class="fa fa-bookmark"></i> {{ activity.pub_date }}</span>
        </div>
    </div>   
</a>

src/Alpaca/templates/Alpaca/shared/visuals/_activity-table.html
{% load i18n %}

<div class="al-table">
        <table>
        <tr>
            <th>
                <a href="?order_by=title&last={{sort_sign}}{{sorted_column}}">
                    {% trans "Title" %}
                    {% if sorted_column == "title" %}
                        <i class="fa {{sort_icon}}" aria-hidden="true"></i>
                    {% else %}
                        <i class="fa fa-sort" aria-hidden="true"></i>
                    {% endif %}
                </a>
            </th>
            <th>
                <a href="?order_by=author&last={{sort_sign}}{{sorted_column}}">
                    {% trans "Author" %}
                    {% if sorted_column == "author" %}
                        <i class="fa {{sort_icon}}" aria-hidden="true"></i>
                    {% else %}
                        <i class="fa fa-sort" aria-hidden="true"></i>
                    {% endif %}
                </a>
            </th>
            <th>
                <a href="?order_by=age_minimum&last={{sort_sign}}{{sorted_column}}">
                    {% trans "Age Minimum" %}
                    {% if sorted_column == "age_minimum" %}
                        <i class="fa {{sort_icon}}" aria-hidden="true"></i>
                    {% else %}
                        <i class="fa fa-sort" aria-hidden="true"></i>
                    {% endif %}
                </a>
            </th>
            <th>
                <a href="?order_by=attendants&last={{sort_sign}}{{sorted_column}}">
                    {% trans "# of Attendants" %}
                    {% if sorted_column == "attendants" %}
                        <i class="fa {{sort_icon}}" aria-hidden="true"></i>
                    {% else %}
                        <i class="fa fa-sort" aria-hidden="true"></i>
                    {% endif %}
                </a>
            </th>
            <th>
                <a href="?order_by=pub_date&last={{sort_sign}}{{sorted_column}}">
                    {% trans "Published Date" %}
                    {% if sorted_column == "pub_date" %}
                        <i class="fa {{sort_icon}}" aria-hidden="true"></i>
                    {% else %}
                        <i class="fa fa-sort" aria-hidden="true"></i>
                    {% endif %}
                </a>
            </th>
            <th>
                <a href="?order_by=next_session&last={{sort_sign}}{{sorted_column}}">
                    {% trans "Next Session" %}
                    {% if sorted_column == "next_session" %}
                        <i class="fa {{sort_icon}}" aria-hidden="true"></i>
                    {% else %}
                        <i class="fa fa-sort" aria-hidden="true"></i>
                    {% endif %}
                </a>
            </th>
        </tr>
        {% for activity in activity_list %}
        <tr>
            <td><a href="{% url 'alpaca:activity' activity.id %}">{{ activity.title }}</a></td>
            <td><a href="{% url 'alpaca:profile' activity.author.username %}">{{ activity.author }}</a></td>
            <td class="text-center">{{ activity.age_minimum }} {% trans "years-old" %}</td>
            <td class="text-center">{{ activity.attendants.count }}</td>
            <td>{{ activity.pub_date }}</td>
            <td>
                {% with activity.get_next_session as next_session %}
                    {% if next_session %}
                        {{ next_session.start_date }}
                    {% elif activity.session_set.count == 0 %}
                        {% trans "No sessions yet" %}
                    {% else %}
                        {% trans "Waiting for future sessions!" %}
                    {% endif %}
                {% endwith %}
            </td>
        </tr>           
        {% endfor %}
    </table>
</div>

src/Alpaca/templates/Alpaca/shared/visuals/_empty.html
<div class="al-empty">
    <p>
        {{ message }}
    </p>
</div>

src/Alpaca/templates/Alpaca/shared/visuals/_event-card.html
{% load i18n %}


<a class="al-card" href="{% url 'alpaca:event' event.id %}">
    {% if event.cover and event.cover.name != "False" %}
        <div class="al-card-cover" style="background-image: url({{event.cover.url}});">  
        </div>
    {% endif %}
    <div class="al-card-body">
        <div class="al-card-header">
            <h1>{{ event.title }} <span class="al-text-tail">{% trans "by" %} {{ event.group.name }}</span></h1>
            <div class="al-card-descriptors">       
                <span class="next-session"><i class="fa fa-calendar-check-o"></i> {{ event.start_date }}</span>                    
                <span class="at-descriptor"><i class="fa fa-map-marker"></i> {{ event.city }}</span>
                <span class="attendant-count"><i class="fa fa-user"></i> {{ event.num_attendants }}</span>
                
                {% if event.age_minimum >= 18 %}
                    <span class="adults-only">+18</span>
                {% endif %}
            </div>
        </div>

        <div class="al-card-text">
            {{ event.get_short_description | safe }}
        </div>
        
        <div class="al-card-footer">
            <span class="al-card-pub-date"><i class="fa fa-bookmark"></i> {{ event.pub_date }}</span>
        </div>
    </div>   
</a>

src/Alpaca/templates/Alpaca/shared/visuals/_filter-bar.html
{% load i18n %}

<small>{% trans "Filters:" %}</small>
<a class="al-button al-button-inline" href="?filter=all"> <span>{% trans "All Activities" %}</span> </a>
<a class="al-button al-button-inline" href="?filter=author"> <span>{% trans "My Activities: Author" %}</span> </a>
<a class="al-button al-button-inline" href="?filter=attendant"> <span>{% trans "My Activities: Attendant" %}</span></a>                

src/Alpaca/templates/Alpaca/shared/visuals/_filter-panel.html
{% load i18n %}

<div class="al-sidebar-section">
    {% comment %} TODO: Fully translate {% endcomment %}
    <h2 class="al-sidebar-section-title">{% trans "Show" %}</h2>
    <form name="filter_form" method="GET" class="al-form-base">
        <input type="radio" name="filter" onclick="location.href=this.value;" value="?filter=all" 
            {% if current_filter == "all" or current_filter is None%} checked {% endif %}> 
                <span>{% trans "All Activities" %}</span> 
        <br>
        <input type="radio" name="filter" onclick="location.href=this.value;" value="?filter=author"
            {% if current_filter == "author" %} checked {% endif %}> 
                <span>Las que organizo</span> 
        <br>
        <input type="radio" name="filter" onclick="location.href=this.value;" value="?filter=attendant"
            {% if current_filter == "attendant" %} checked {% endif %}> 
                <span>En las que participo</span>
    </form>
</div>

src/Alpaca/templates/Alpaca/shared/visuals/_form-panel.html
{% load i18n %}

<div class="al-content-panel al-content-sidebar">
    <h2>{{ form_title }}</h2>
    <form method="POST" class="al-panel-form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="al-submit-wrapper">
            <input type="submit" class="al-button al-button-inline" name="{{ form_name }}" value="{{ submit_text }}"/>
        </div>
    </form>

    {% if rich_field_name is not None and rich_field_name != "" %}
        <script>
            CKEDITOR.replace( '{{ rich_field_name }}' );
        </script>
    {% endif %}
    {% block other-content %}{% endblock %}
</div>

src/Alpaca/templates/Alpaca/shared/visuals/_location-filter-panel.html
{% load i18n %}

<div class="al-content-panel al-content-sidebar">
    <small>{% trans "Where" %}</small>
    <form name="location_form" method="GET" class="al-form-base al-panel-form">
        <input type="radio" name="filter" onclick="location.href=this.value;" value="?location=here" 
            {% if current_filter == "here" or current_filter is None%} checked {% endif %}> 
                <span>{% trans "My location" %}</span> 
        <br>
        <input type="radio" name="filter" onclick="location.href=this.value;" value="?location=select"
            {% if current_filter == "select" %} checked {% endif %}> 
                <select></select>
       
    </form>
</div>

            

src/Alpaca/templates/Alpaca/shared/visuals/_order-bar-item.html
{% load i18n %}

<a class="al-order-bar-item {% if sorted_column == column_key %}al-order-bar-item--active{% endif %}" href="?order_by={{column_key}}&last={{sort_sign}}{{sorted_column}}">
    {% trans column_name %}
    {% if sorted_column == column_key %}
        <i class="fa {{sort_icon}}" aria-hidden="true"></i>
    {% else %}
        <i class="fa fa-sort" aria-hidden="true"></i>
    {% endif %}
</a>

src/Alpaca/templates/Alpaca/shared/visuals/_order-bar.html
{% load i18n %}

<div class="al-order-bar">
    {% include "./_order-bar-item.html" with column_key="title" column_name="Title" %}
    {% include "./_order-bar-item.html" with column_key="author" column_name="Author" %}
    {% include "./_order-bar-item.html" with column_key="city" column_name="City" %}
    {% include "./_order-bar-item.html" with column_key="pub_date" column_name="Published Date" %}
    {% include "./_order-bar-item.html" with column_key="next_session" column_name="Next Session" %}
    {% include "./_order-bar-item.html" with column_key="age_minimum" column_name="Age Minimum" %}
    {% include "./_order-bar-item.html" with column_key="num_attendants" column_name="# of Attendants" %}
</div>

src/Alpaca/templates/Alpaca/shared/visuals/_search-bar.html
{% load i18n %}

<form class="al-search-bar al-flex-row al-flex-align-end" name="search_form" method="GET">
    <i class="fa fa-search al-search-bar-magnifier" aria-hidden="true"></i>
    <input type="text" class="al-search-bar-input" name="search" placeholder="{% trans 'Search...' %}">
</form>

src/Alpaca/templates/Alpaca/shared/visuals/_tag.html
<div class="al-tag">
    <div class="al-tag-icon-wrapper">
        <i class="fa fa-{{ icon }}"></i>
    </div>
    <div class="al-tag-text">
        <span>{{ text }}</span>
    </div>
</div>

src/Alpaca/templates/Alpaca/shared/visuals/_when-panel.html
{% load i18n %}

<div class="al-sidebar-section al-when-panel">
    <h2 class="al-sidebar-section-title">{{ form_title }}</h2>
    <form method="POST" class="al-form-base">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="al-submit-wrapper">
            <input type="submit" class="al-button" name="{{ form_name }}" value="{{ submit_text }}"/>
        </div>
    </form>

    {% if rich_field_name is not None and rich_field_name != "" %}
        <script>
            CKEDITOR.replace( '{{ rich_field_name }}' );
        </script>
    {% endif %}
    {% block other-content %}{% endblock %}
</div>