src/Alpaca/urls.py
from django.conf.urls import url

import views

app_name = "alpaca"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/group/$', views.group_index, name='group_index'),
    url(r'^index/event/$', views.event_index, name='event_index'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^terms_conditions/$', views.terms_conditions, name='terms_conditions'),

    url(r'^forgotpassword/$', views.forgot_password, name="forgot_password"),
    url(r'^resetpassword$', views.reset_password, name='reset_password'),

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate$', views.activate, name='activate'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^profile/(?P<username>\w+)$', views.profile, name='profile'),
    url(r'^editprofile$', views.edit_profile, name='edit_profile'),
    url(r'^changepassword/$', views.change_password, name="change_password"),

    url(r'^group/new/$', views.new_group, name='new_group'),
    url(r'^group/(?P<group_id>[0-9]+)$', views.group, name='group'),
    url(r'^group/(?P<group_id>[0-9]+)/edit/$', views.edit_group, name='edit_group'),
    url(r'^group/join/(?P<group_id>[0-9]+)$', views.join_group, name='join_group'),
    url(r'^group/leave/(?P<group_id>[0-9]+)$', views.leave_group, name='leave_group'),
    url(r'^group/action/(?P<group_id>[0-9]+)$', views.handle_member, name='handle_member'),
    url(r'^group/demote/(?P<group_id>[0-9]+)$', views.demote_admin, name='demote_admin'),
    url(r'^group/members/(?P<group_id>[0-9]+)$', views.group_pending_members, name='group_pending_members'),
    url(r'^group/activities/(?P<group_id>[0-9]+)$', views.group_pending_activities, name='group_pending_activities'),

    url(r'^activity/new/$', views.new_activity, name='new_activity'),
    url(r'^activity/(?P<activity_id>[0-9]+)$', views.activity, name='activity'),
    url(r'^activity/(?P<activity_id>[0-9]+)/edit/$', views.edit_activity, name='edit_activity'),
    url(r'^activity/join/(?P<activity_id>[0-9]+)$', views.join_activity, name='join_activity'),
    url(r'^activity/leave/(?P<activity_id>[0-9]+)$', views.leave_activity, name='leave_activity'),
    url(r'^activity/kick/(?P<activity_id>[0-9]+)$', views.activity_kick_attendant, name='activity_kick_attendant'),
    url(r'^activity/pending/(?P<activity_id>[0-9]+)$', views.activity_pending_requests, name='activity_pending_attendants'),

    url(r'^activity/(?P<activity_id>[0-9]+)/new/$', views.new_session, name='new_session'),
    url(r'^activity/(?P<activity_id>[0-9]+)/edit/(?P<session_id>[0-9]+)$', views.edit_session, name='edit_session'),
    url(r'^activity/(?P<activity_id>[0-9]+)/confirm/$', views.confirm_session, name='confirm_session'),

    url(r'^event/new/(?P<group_id>[0-9]+)$', views.new_event, name='new_event'),
    url(r'^event/(?P<event_id>[0-9]+)$', views.event, name='event'),
    url(r'^event/(?P<event_id>[0-9]+)/edit/$', views.edit_event, name='edit_event'),
    url(r'^event/join/(?P<event_id>[0-9]+)$', views.join_event, name='join_event'),
    url(r'^event/leave/(?P<event_id>[0-9]+)$', views.leave_event, name='leave_event'),
    url(r'^event/kick/(?P<event_id>[0-9]+)$', views.event_kick_attendant, name='event_kick_attendant'),
    url(r'^event/attendants/(?P<event_id>[0-9]+)$', views.event_pending_attendants, name='event_pending_attendants'),
    url(r'^event/activities/(?P<event_id>[0-9]+)$', views.event_pending_activities, name='event_pending_activities'),
    url(r'^event/(?P<event_id>[0-9]+)/activity/new/$', views.event_new_activity, name='event_new_activity'),
]

src/WarLlama/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('Alpaca.urls')) ## Enabling translation
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

## About Multi-Language, quoting: 
## http://stackoverflow.com/questions/10280881/django-site-with-2-languages/26520044#26520044
# Wrap your text with lazytext! import lazytext (as above) and wrap every string 
# with it like so _('text'), you can even go to your other urls.py files and do url 
# translation like so:
#
# >>> url(_(r'^dual_language/$'), landing, name='duallang_landing'), <<<
#
# You can wrap text that you want translated in your other files, such as models.py, 
# views.py etc.. Here is an example model field with translations for label and help_text:
#
# >>> name = models.CharField(_('name'), max_length=255, unique=True, help_text=_("Name of the FAQ Topic")) <<<
#
# Django translation docs are great for this!

src/Alpaca/views/activity.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from django.views.generic import *
from django.core.urlresolvers import reverse

from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils.translation import ugettext_lazy as _ ## For Multi-Language

from itertools import chain

from ..models import Activity, Session
from ..forms import ActivityForm
from ..utils import set_translation, handle_form

import datetime


## -- ACTIVITIES -- ##
def activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user
    session_list = activity.session_set.order_by('start_date')
    context = { 'user': user,
                'activity': activity,
                'session_list': session_list}




    if user.is_authenticated:
        context['user_has_actions'] = True

        if activity.pending_event != None:
            context['user_has_actions'] = False
            context['why_not_message'] = _("This activity is waiting to be part of an event! Come back later :)")        

        elif activity.event != None and not activity.event.is_user_attending(user):
            context['user_has_actions'] = False
            context['why_not_message'] = _("This activity is part of an event. Join the event to attend this activity!")        
            
        elif not activity.is_user_old_enough(user):
            context['user_has_actions'] = False
            context['why_not_message'] = _("You are too young to attend this activity.")

        elif user in activity.pending_attendants.all():
            context['user_has_actions'] = False
            context['why_not_message'] = _("The author of this activity has received your request to join!") 

        if user == activity.author:
            return render(request, 'Alpaca/activity/activity_author.html', context)
        else:
            return render(request, 'Alpaca/activity/activity_user.html', context)
    else:        
        return render(request, 'Alpaca/activity/activity_anon.html', context)

@login_required
def new_activity(request):
    set_translation(request)    
    user = request.user    

    context = { 'form_title': _("Start a new activity"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }

    user_groups = user.profile.get_groups()

    if request.method == "POST":
        form = ActivityForm(user_groups, request.POST, request.FILES )
        if form.is_valid():
           activity = form.save_new(user)        
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForm(group_list=user_groups) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def edit_activity(request, activity_id):
    set_translation(request)
    user = request.user
    activity = get_object_or_404(Activity, pk=activity_id)
    if user != activity.author:
        return  HttpResponseRedirect(reverse('alpaca:index'))
 
    if activity.group != None or activity.pending_group != None:
        user_groups = [activity.group.id]
    else:
        user_groups = user.profile.get_groups()
    
    context = { 'form_title': _("Editing activity") + " " + activity.title,
                'submit_text': _("Save changes"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = ActivityForm(user_groups, request.POST, request.FILES, instance=activity)
        if form.is_valid():
           activity = form.save()   
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForm(group_list=user_groups, instance=activity) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def join_activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user

    if request.method == "POST":
        activity.join(user)

    return HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def leave_activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user

    if request.method == "POST":
        activity.leave(user)

    return HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def activity_kick_attendant(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("attending"))
        activity.kick(selected_user)

    return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def activity_pending_requests(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("user_join_request"))
        activity.handle_user_request(selected_user, "accept_request" in request.POST)

    return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))

src/Alpaca/views/event.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from django.views.generic import *
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils import timezone
from django.utils.translation import ugettext_lazy as _ ## For Multi-Language

from ..models import Profile, Group, Event, Activity
from ..forms import EventForm, ActivityForEventForm
from ..emails import email_reset_password

from ..utils import set_translation, sort_activities

import datetime


def event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    to_sort_column = request.GET.get('order_by')
    sorted_column = request.GET.get('last')
    context = sort_activities(Activity.objects.filter(event_id=event.id), to_sort_column, sorted_column)

    context['user'] = request.user
    context['event'] = event

    if user.is_authenticated:
        context['user_is_old_enough'] = event.is_user_old_enough(user)
        if user == event.group.superuser or user in event.group.admin_list.all():
            return render(request, 'Alpaca/event/event_admin.html', context)
        else:
            return render(request, 'Alpaca/event/event_user.html', context)
    else:        
        return render(request, 'Alpaca/event/event_anon.html', context)

@login_required
def new_event(request, group_id):
    set_translation(request)
    
    user = request.user
    group = get_object_or_404(Group, pk=group_id)

    if user != group.superuser and user not in group.admin_list.all():
        return  HttpResponseRedirect(reverse('alpaca:index'))
    

    context = { 'form_title': _("Start a new event!"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save_new(group)                     
            return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event.id}))
        else:
            context['form'] = form
            return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)

    else:
        context['form'] = EventForm() 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def edit_event(request, event_id):
    set_translation(request)
    user = request.user
    event = get_object_or_404(Event, pk=event_id)
    
    if user != event.group.superuser and user not in event.group.admin_list.all():
        return  HttpResponseRedirect(reverse('alpaca:index'))

    context = { 'form_title': _("Editing event") + " " + event.title,
                'submit_text': _("Save changes"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            event = form.save()
            return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event.id}))
        else:
            context['form'] = form
            return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)

    else:
        context['form'] = EventForm(instance=event)
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


## USER ACTIONS ##
@login_required
def join_event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    if request.method == "POST":
        event.join(user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def leave_event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    if request.method == "POST":
        event.leave(user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))

@login_required
def event_new_activity(request, event_id):
    user = request.user
    event = get_object_or_404(Event, pk=event_id)

    if not event.is_user_attending(user):
        return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))
    
    context = { 'form_title': _("Start a new activity"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }
    
    if request.method == "POST":
        form = ActivityForEventForm(event.group, event, request.POST, request.FILES )
        if form.is_valid():
           activity = form.save_new(user)        
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForEventForm(group=event.group, event=event) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    


## ADMIN ACTIONS ##
@login_required
def event_kick_attendant(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("attending"))
        event.kick(selected_user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def event_pending_attendants(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("user_join_request"))
        event.handle_user_request(selected_user, "accept_request" in request.POST)

    return HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def event_pending_activities(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_activity = get_object_or_404(Activity, id=request.POST.get("activity_request"))
        event.handle_activity_request(selected_activity, "accept_request" in request.POST)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))

src/Alpaca/templates/Alpaca/event/_event-layout.html
{% extends '../shared/layouts/_layout.html' %}
{% load i18n %}

{% block content %}

    <div class="al-panel al-margin-top">
        {% if not event.banner or event.banner.name == "False" %}
            <div class="al-event-title">
                <h1>{{ event.title }}</h1>
            </div>
        {% else %}
            <div class="al-event-banner" style="background-image: url({{event.banner.url}});">
                {% if event.show_title %}
                    <h1>{{ event.title }}</h1>
                {% endif %}
            </div>
        {% endif %}

        <div class="al-event-banner-footer al-flex-row">
            <div class="al-flex-grow al-event-banner-footer-info">
                <span class="al-event-banner-footer-info-date">
                    <i class="fa fa-calendar"></i>
                    <b>{{ event.start_date }}</b>
                </span>
                <span class="al-event-banner-footer-info-location">
                    <i class="fa fa-map-marker"></i>
                    <b>{{ event.city }}</b>
                </span>
            </div>
            <div class="al-event-banner-footer-actions">
                {% block user_options %}{% endblock %}
            </div>
        </div>
    </div>

    <div class="al-flex-row al-flex-align-start al-flex-stretch-content">
        <div class="al-flex-grow">
            <div class="al-content-panel">
                {{ event.description | safe }}
            </div>

            <h3 class="al-section-title">
                <span>{% trans "Activity List" %}</span>
            </h3>

            {% if event.activity_list.count <= 0 %}
                <p>{% trans "No activities yet!" %}</p>
            {% else %}
                {% comment %}{% include "../shared/visuals/_order-bar.html" %}{% endcomment %}
                {% for activity in event.activity_list.all %}
                    {% include "../shared/visuals/_activity-card.html" %}                
                {% endfor %}
            {% endif %}

        </div>
        <div class="al-event-sidebar">

            <div class="al-event-sidebar-section">
                <h4 class="al-event-sidebar-section-header">{% trans "Settings:" %}</h4>
                <p>
                    {% if event.group_only_attendants %}
                        <b> {% trans "Only" %} {{ event.group.name }} {% trans "members" %} </b>
                    {% else %}
                        <b> {% trans "Any user" %}</b>
                    {% endif %}    
                    {% trans "can join this event." %} </p>
                    <p>{% trans "Users may join this event" %}
                    {% if event.auto_register_users %}
                        <b> {% trans "freely." %}</b>
                    {% else %}
                        <b> {% trans "upon request." %}</b>
                    {% endif %}    
                    </p>
                    <p>{% trans "Activities may join this event" %}
                    {% if event.auto_register_activities %}
                        <b> {% trans "freely." %}</b>
                    {% else %}
                        <b> {% trans "upon request." %}</b>
                    {% endif %}    
                </p>
            </div>

            <hr>

            <div class="al-event-sidebar-section">
                <h4 class="al-event-sidebar-section-header">{% trans "Attendants:" %}</h4>
                <ul class="al-activity-detail-attendants-list">
                    {% block attendants %}{% endblock %}
                </ul>
            </div>

            {% block user_requests %}{% endblock %}

            {% block activity_requests %}{% endblock %}

        </div>
    </div>

{% endblock %}

src/Alpaca/templates/Alpaca/event/event_admin.html
{% extends './_event-layout.html' %}
{% load i18n %}

{% block user_options %}    
    <a class="al-button al-button-inline" href="{% url 'alpaca:edit_event' event.id %}">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> <span>{% trans "Edit" %}</span>
    </a>
    <a class="al-button al-button-inline" href="{% url 'alpaca:event_new_activity' event.id %}">
        <i class="fa fa-plus" aria-hidden="true"></i> <span>{% trans "New Activity" %}</span>
    </a>
{% endblock %}

{% block attendants %}
    {% if event.attendants.count <= 0 %}
        <p>{% trans "There are no users attending your event." %}</p>
    {% else %}
        <form action="{% url 'alpaca:event_kick_attendant' event.id %}" method="POST">
            {% csrf_token %}
            <select id="attending_users" name="attending">
            {% for att in event.attendants.all %}
                <option value="{{att.id}}">{{ att.username }}</option>
            {% endfor %}
            </select>
            <input type="submit" class="al-button al-button-inline" name="kick_participant" value="{% trans 'Kick out' %}"/>
        </form>
    {% endif %}
{% endblock %}

{% block user_requests %}
    <hr>
    <div class="al-event-sidebar-section">
        <h4 class="al-event-sidebar-section-header">{% trans "Attending requests:" %}</h4>
        {% if event.pending_attendants.count <= 0 %}
            <p>{% trans "There are no pending requests to attend the event." %}</p>
        {% else %}
            <p>{% trans "Manage the requests to attend the event:" %}</p>
            <form action="{% url 'alpaca:event_pending_attendants' event.id %}" method="POST">
                {% csrf_token %}
                <select id="pending_requests" name="user_join_request">
                {% for att in event.pending_attendants.all %}
                    <option value="{{att.id}}">{{ att.username }}</option>
                {% endfor %}
                </select>
                <input type="submit" class="al-button al-button-inline" name="accept_request" value="{% trans 'Accept' %}"/>
                <input type="submit" class="al-button al-button-inline" name="reject_request" value="{% trans 'Reject' %}"/>
            </form>  
        {% endif %}
    </div>
{% endblock %}
    
{% block activity_requests %}
    <hr>
    <div class="al-event-sidebar-section">
        <h4 class="al-event-sidebar-section-header">{% trans "Activity requests:" %}</h4>
        {% if event.pending_activities.count <= 0 %}
            <p>{% trans "There are no pending activities to confirm." %}</p>
        {% else %}
            <p>{% trans "Manage the activities that want to be related to this event:" %}</p>
            <form action="{% url 'alpaca:event_pending_activities' event.id %}" method="POST">
                {% csrf_token %}
                <select id="pending_requests" name="activity_request">
                {% for act in event.pending_activities.all %}
                    <option value="{{act.id}}">{{ act.title }}</option>
                {% endfor %}
                </select>
                <input type="submit" class="al-button al-button-inline" name="accept_request" value="{% trans 'Accept' %}"/>
                <input type="submit" class="al-button al-button-inline" name="reject_request" value="{% trans 'Reject' %}"/>
            </form>  
        {% endif %}
    </div>

{% endblock %}

src/Alpaca/templates/Alpaca/event/event_anon.html
{% extends './_event-layout.html' %}
{% load i18n %}

{% block user_options %}
    <a class="al-button al-button-inline" href="{% url 'alpaca:login' %}">
        {% trans "Join" %}
    </a>
{% endblock %}

{% block attendants %}
    {% if event.attendants.count <= 0 %}
        <p>{% trans "There are no users attending this event, except" %} {{ event.author }}.</p>
    {% else %}    
        {% for att in event.attendants.all %}
            <li class="al-activity-detail-attendants-list-item">
                {% include "../shared/visuals/_user-widget.html" with user=att %}
            </li>
        {% endfor %}
    {% endif %}
{% endblock %}

src/Alpaca/templates/Alpaca/event/event_user.html
{% extends './_event-layout.html' %}
{% load i18n %}

{% block user_options %}    
    {% if not user_is_old_enough %}
        <p>{% trans "You are too young to attend this event." %}</p>
    {% elif event.group_only_attendants and user not in event.group.member_list.all %}
        <p>{% trans "Only" %} {{event.group.name}} {% trans "members can join this event." %}</p>
    {% elif user in event.pending_attendants.all %}
        <p>{% trans "The organizers have received your request to join!" %}</p>
    {% elif user in event.attendants.all %}
        <form action="{% url 'alpaca:leave_event' event.id %}" method="POST" style="display: inline-block;">
            {% csrf_token %}
            <input class="al-button al-button-inline" type="submit" name="leave_event" value="{% trans 'Leave' %}"/>
        </form>
        <a class="al-button al-button-inline" href="{% url 'alpaca:event_new_activity' event.id %}">
            <i class="fa fa-plus" aria-hidden="true"></i> <span>{% trans "New Activity" %}</span>
        </a>
    {% else %}
        <form action="{% url 'alpaca:join_event' event.id %}" method="POST">
            {% csrf_token %}
            <input class="al-button al-button-inline" type="submit" name="join_event" value="{% trans 'Join!' %}"/>
        </form>
    {% endif %}
{% endblock %}

{% block attendants %}
    {% if event.attendants.count <= 0 %}
        <p>{% trans "There are no users attending this event yet, be the first one!" %}</p>
    {% else %}    
        {% for att in event.attendants.all %}
            <li class="al-activity-detail-attendants-list-item">
                {% include "../shared/visuals/_user-widget.html" with user=att %}
            </li>
        {% endfor %}
    {% endif %}
{% endblock %}