src/Alpaca/urls.py
from django.conf.urls import url

import views

app_name = "alpaca"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/group/$', views.group_index, name='group_index'),
    url(r'^index/event/$', views.event_index, name='event_index'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^terms_conditions/$', views.terms_conditions, name='terms_conditions'),

    url(r'^forgotpassword/$', views.forgot_password, name="forgot_password"),
    url(r'^resetpassword$', views.reset_password, name='reset_password'),

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate$', views.activate, name='activate'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^profile/(?P<username>\w+)$', views.profile, name='profile'),
    url(r'^editprofile$', views.edit_profile, name='edit_profile'),
    url(r'^changepassword/$', views.change_password, name="change_password"),

    url(r'^group/new/$', views.new_group, name='new_group'),
    url(r'^group/(?P<group_id>[0-9]+)$', views.group, name='group'),
    url(r'^group/(?P<group_id>[0-9]+)/edit/$', views.edit_group, name='edit_group'),
    url(r'^group/join/(?P<group_id>[0-9]+)$', views.join_group, name='join_group'),
    url(r'^group/leave/(?P<group_id>[0-9]+)$', views.leave_group, name='leave_group'),
    url(r'^group/action/(?P<group_id>[0-9]+)$', views.handle_member, name='handle_member'),
    url(r'^group/demote/(?P<group_id>[0-9]+)$', views.demote_admin, name='demote_admin'),
    url(r'^group/members/(?P<group_id>[0-9]+)$', views.group_pending_members, name='group_pending_members'),
    url(r'^group/activities/(?P<group_id>[0-9]+)$', views.group_pending_activities, name='group_pending_activities'),

    url(r'^activity/new/$', views.new_activity, name='new_activity'),
    url(r'^activity/(?P<activity_id>[0-9]+)$', views.activity, name='activity'),
    url(r'^activity/(?P<activity_id>[0-9]+)/edit/$', views.edit_activity, name='edit_activity'),
    url(r'^activity/join/(?P<activity_id>[0-9]+)$', views.join_activity, name='join_activity'),
    url(r'^activity/leave/(?P<activity_id>[0-9]+)$', views.leave_activity, name='leave_activity'),
    url(r'^activity/kick/(?P<activity_id>[0-9]+)$', views.activity_kick_attendant, name='activity_kick_attendant'),
    url(r'^activity/pending/(?P<activity_id>[0-9]+)$', views.activity_pending_requests, name='activity_pending_attendants'),

    url(r'^activity/(?P<activity_id>[0-9]+)/new/$', views.new_session, name='new_session'),
    url(r'^activity/(?P<activity_id>[0-9]+)/edit/(?P<session_id>[0-9]+)$', views.edit_session, name='edit_session'),
    url(r'^activity/(?P<activity_id>[0-9]+)/confirm/$', views.confirm_session, name='confirm_session'),

    url(r'^event/new/(?P<group_id>[0-9]+)$', views.new_event, name='new_event'),
    url(r'^event/(?P<event_id>[0-9]+)$', views.event, name='event'),
    url(r'^event/(?P<event_id>[0-9]+)/edit/$', views.edit_event, name='edit_event'),
    url(r'^event/join/(?P<event_id>[0-9]+)$', views.join_event, name='join_event'),
    url(r'^event/leave/(?P<event_id>[0-9]+)$', views.leave_event, name='leave_event'),
    url(r'^event/kick/(?P<event_id>[0-9]+)$', views.event_kick_attendant, name='event_kick_attendant'),
    url(r'^event/attendants/(?P<event_id>[0-9]+)$', views.event_pending_attendants, name='event_pending_attendants'),
    url(r'^event/activities/(?P<event_id>[0-9]+)$', views.event_pending_activities, name='event_pending_activities'),
    url(r'^event/(?P<event_id>[0-9]+)/activity/new/$', views.event_new_activity, name='event_new_activity'),
]

src/WarLlama/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('Alpaca.urls')) ## Enabling translation
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

## About Multi-Language, quoting: 
## http://stackoverflow.com/questions/10280881/django-site-with-2-languages/26520044#26520044
# Wrap your text with lazytext! import lazytext (as above) and wrap every string 
# with it like so _('text'), you can even go to your other urls.py files and do url 
# translation like so:
#
# >>> url(_(r'^dual_language/$'), landing, name='duallang_landing'), <<<
#
# You can wrap text that you want translated in your other files, such as models.py, 
# views.py etc.. Here is an example model field with translations for label and help_text:
#
# >>> name = models.CharField(_('name'), max_length=255, unique=True, help_text=_("Name of the FAQ Topic")) <<<
#
# Django translation docs are great for this!

src/Alpaca/views/activity.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from django.views.generic import *
from django.core.urlresolvers import reverse

from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils.translation import ugettext_lazy as _ ## For Multi-Language

from itertools import chain

from ..models import Activity, Session
from ..forms import ActivityForm
from ..utils import set_translation, handle_form

import datetime


## -- ACTIVITIES -- ##
def activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user
    session_list = activity.session_set.order_by('start_date')
    context = { 'user': user,
                'activity': activity,
                'session_list': session_list}




    if user.is_authenticated:
        context['user_has_actions'] = True

        if activity.pending_event != None:
            context['user_has_actions'] = False
            context['why_not_message'] = _("This activity is waiting to be part of an event! Come back later :)")        

        elif activity.event != None and not activity.event.is_user_attending(user):
            context['user_has_actions'] = False
            context['why_not_message'] = _("This activity is part of an event. Join the event to attend this activity!")        
            
        elif not activity.is_user_old_enough(user):
            context['user_has_actions'] = False
            context['why_not_message'] = _("You are too young to attend this activity.")

        elif user in activity.pending_attendants.all():
            context['user_has_actions'] = False
            context['why_not_message'] = _("The author of this activity has received your request to join!") 

        if user == activity.author:
            return render(request, 'Alpaca/activity/activity_author.html', context)
        else:
            return render(request, 'Alpaca/activity/activity_user.html', context)
    else:        
        return render(request, 'Alpaca/activity/activity_anon.html', context)

@login_required
def new_activity(request):
    set_translation(request)    
    user = request.user    

    context = { 'form_title': _("Start a new activity"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }

    user_groups = user.profile.get_groups()

    if request.method == "POST":
        form = ActivityForm(user_groups, request.POST, request.FILES )
        if form.is_valid():
           activity = form.save_new(user)        
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForm(group_list=user_groups) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def edit_activity(request, activity_id):
    set_translation(request)
    user = request.user
    activity = get_object_or_404(Activity, pk=activity_id)
    if user != activity.author:
        return  HttpResponseRedirect(reverse('alpaca:index'))
 
    if activity.group != None or activity.pending_group != None:
        user_groups = [activity.group.id]
    else:
        user_groups = user.profile.get_groups()
    
    context = { 'form_title': _("Editing activity") + " " + activity.title,
                'submit_text': _("Save changes"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = ActivityForm(user_groups, request.POST, request.FILES, instance=activity)
        if form.is_valid():
           activity = form.save()   
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForm(group_list=user_groups, instance=activity) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def join_activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user

    if request.method == "POST":
        activity.join(user)

    return HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def leave_activity(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)
    user = request.user

    if request.method == "POST":
        activity.leave(user)

    return HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def activity_kick_attendant(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("attending"))
        activity.kick(selected_user)

    return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))


@login_required
def activity_pending_requests(request, activity_id):
    set_translation(request)
    activity = get_object_or_404(Activity, pk=activity_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("user_join_request"))
        activity.handle_user_request(selected_user, "accept_request" in request.POST)

    return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity_id}))

src/Alpaca/views/event.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

from django.views.generic import *
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.utils import timezone
from django.utils.translation import ugettext_lazy as _ ## For Multi-Language

from ..models import Profile, Group, Event, Activity
from ..forms import EventForm, ActivityForEventForm
from ..emails import email_reset_password

from ..utils import set_translation, sort_activities

import datetime


def event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    to_sort_column = request.GET.get('order_by')
    sorted_column = request.GET.get('last')
    context = sort_activities(Activity.objects.filter(event_id=event.id), to_sort_column, sorted_column)

    context['user'] = request.user
    context['event'] = event

    if user.is_authenticated:
        context['user_is_old_enough'] = event.is_user_old_enough(user)
        if user == event.group.superuser or user in event.group.admin_list.all():
            return render(request, 'Alpaca/event/event_admin.html', context)
        else:
            return render(request, 'Alpaca/event/event_user.html', context)
    else:        
        return render(request, 'Alpaca/event/event_anon.html', context)

@login_required
def new_event(request, group_id):
    set_translation(request)
    
    user = request.user
    group = get_object_or_404(Group, pk=group_id)

    if user != group.superuser and user not in group.admin_list.all():
        return  HttpResponseRedirect(reverse('alpaca:index'))
    

    context = { 'form_title': _("Start a new event!"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save_new(group)                     
            return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event.id}))
        else:
            context['form'] = form
            return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)

    else:
        context['form'] = EventForm() 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


@login_required
def edit_event(request, event_id):
    set_translation(request)
    user = request.user
    event = get_object_or_404(Event, pk=event_id)
    
    if user != event.group.superuser and user not in event.group.admin_list.all():
        return  HttpResponseRedirect(reverse('alpaca:index'))

    context = { 'form_title': _("Editing event") + " " + event.title,
                'submit_text': _("Save changes"),
                'rich_field_name': "description" }

    if request.method == "POST":
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            event = form.save()
            return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event.id}))
        else:
            context['form'] = form
            return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)

    else:
        context['form'] = EventForm(instance=event)
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)


## USER ACTIONS ##
@login_required
def join_event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    if request.method == "POST":
        event.join(user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def leave_event(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)
    user = request.user

    if request.method == "POST":
        event.leave(user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))

@login_required
def event_new_activity(request, event_id):
    user = request.user
    event = get_object_or_404(Event, pk=event_id)

    if not event.is_user_attending(user):
        return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))
    
    context = { 'form_title': _("Start a new activity"),
                'submit_text': _("Create!"),
                'rich_field_name': "description" }
    
    if request.method == "POST":
        form = ActivityForEventForm(event.group, event, request.POST, request.FILES )
        if form.is_valid():
           activity = form.save_new(user)        
           return  HttpResponseRedirect(reverse('alpaca:activity', kwargs={'activity_id': activity.id} ))
        else:
           context['form'] = form
           return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    else:
        context['form'] = ActivityForEventForm(group=event.group, event=event) 
        return render(request, 'Alpaca/shared/layouts/_form-layout.html', context)
    


## ADMIN ACTIONS ##
@login_required
def event_kick_attendant(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("attending"))
        event.kick(selected_user)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def event_pending_attendants(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_user = get_object_or_404(User, id=request.POST.get("user_join_request"))
        event.handle_user_request(selected_user, "accept_request" in request.POST)

    return HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))


@login_required
def event_pending_activities(request, event_id):
    set_translation(request)
    event = get_object_or_404(Event, pk=event_id)

    if request.method == "POST":
        selected_activity = get_object_or_404(Activity, id=request.POST.get("activity_request"))
        event.handle_activity_request(selected_activity, "accept_request" in request.POST)

    return  HttpResponseRedirect(reverse('alpaca:event', kwargs={'event_id': event_id}))

src/Alpaca/templates/Alpaca/shared/layouts/_floating-box-layout.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Alpaca</title>
        <link rel="stylesheet" href="{% static "main.css" %}">
    </head>
    <body>
        <div class="al-floating-box">
            <div class="al-floating-box-title">
                <img class="al-floating-box-title-image" src="{% static 'alpaca-logo-orange.svg' %}" draggable="false">
            </div>
            <div class="al-floating-box-content al-content-panel">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

src/Alpaca/templates/Alpaca/shared/layouts/_form-floating-layout.html
{% extends './_floating-box-layout.html' %}

{% block content %}
    <form method="POST" class="al-form-base">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <input class="al-button" type="submit" value="{{ submit_text }}"/>
        </p>
    </form>
    {% if rich_field_name != "" %}
    <script>
        CKEDITOR.replace( '{{ rich_field_name }}' );
    </script>
    {% endif %}
    
    {% block other-content %}{% endblock %}
{% endblock %}

src/Alpaca/templates/Alpaca/shared/layouts/_form-layout.html
{% extends './_layout.html' %}
{% load i18n %}

{% block title %}{% endblock %}
{% block content %}

<h1 class="al-title">{{form_title}}</h1>

<div class="al-content-panel">    
    <form method="POST" enctype="multipart/form-data" class="al-form-base al-layout-form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="al-margin-top al-margin-bottom">
            <input class="al-button al-button-inline al-float-right" type="submit" value="{{ submit_text }}"></input>
            <div class="clear-fix"></div>
        </div>
    </form>

    {% if rich_field_name != "" %}
    <script>
        CKEDITOR.replace( '{{ rich_field_name }}' );
    </script>
    {% endif %}
    {% block other-content %}{% endblock %}
</div>
{% endblock %}

src/Alpaca/templates/Alpaca/shared/layouts/_layout.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Alpaca</title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
        <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}">
        <link rel="stylesheet" href="{% static "main.css" %}">
        {% include "../visuals/_ckeditor.html" %}
    </head>
    <body>
        <div class="al-header">
            <div class="al-header-content al-flex-row">
                <div class="al-flex-row al-header-logo-wrapper">
                    <a href="/">
                        <div class="al-header-logo">
                            <div class="al-header-logo-face" style="background-image: url({% static 'Al-Paquita_Branding.png' %});"></div>
                            <img class="al-header-logo-title" src="{% static 'alpaca-logo-white.svg' %}" draggable="false" />
                        </div>
                    </a>
                    <h3 class="al-header-subtitle">ß</h3>
                </div>
                <div class="al-header-navigation al-flex-grow">
                    {% url 'alpaca:index' as index_url %}
                    {% url 'alpaca:group_index' as group_index_url %}
                    {% url 'alpaca:event_index' as event_index_url %}

                    {% if user.is_authenticated %}
                        {% if request.path == index_url %}
                            <a href="{% url 'alpaca:new_activity' %}" class="al-button al-button-inline al-header-navigation-action">
                                <i class="fa fa-plus" aria-hidden="true"></i> 
                                <span>{% trans "New Activity" %}</span>
                            </a>
                        {% endif %}

                        {% if request.path == group_index_url %}
                            <a href="{% url 'alpaca:new_group' %}" class="al-button al-button-inline al-header-navigation-action">
                                <i class="fa fa-plus" aria-hidden="true"></i> 
                                <span>{% trans "New Group" %}</span>
                            </a>
                        {% endif %}
                    {% endif %}

                    {% spaceless %}
                    <a 
                    class="al-header-navigation-option {% if request.path == index_url %}active{% endif %}"
                    href="{{ index_url }}">{% trans "Activities" %}</a>
                    <a 
                    class="al-header-navigation-option {% if request.path == group_index_url %}active{% endif %}"
                    href="{{ group_index_url }}">{% trans "Groups" %}</a>
                    <a 
                    class="al-header-navigation-option {% if request.path == event_index_url %}active{% endif %}"
                    href="{{ event_index_url }}">{% trans "Events" %}</a>
                    {% endspaceless %}
                </div>
                <div class="al-header-menu al-flex-row">
                    {% comment %}<a href="{% url 'alpaca:group_index'%}"> {% trans "Group List" %}</a>{% endcomment %}
                    {% if user.is_authenticated %}
                        <a href="/profile/{{user.username}}">
                            <i class="fa fa-sliders"></i> 
                            <span>{{user.username}}</span>
                        </a>
                        <div class="al-avatar-miniature" style="background-image: url({{user.profile.avatar.url}})"></div>
                        <a href="/logout/"><i class="fa fa-sign-out"></i> {% trans "Log out" %}</a>
                    {% else %}
                        <a href="/login/"><i class="fa fa-sign-in"></i> {% trans "Log in" %}</a>
                        <a href="/signup/"><i class="fa fa-thumbs-up"></i> {% trans "Sign up" %}</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="al-content-wrapper">
            {% block title %}{% endblock %}
            {% block content %}{% endblock %}
        </div>

        <div class="al-footer">
            <div class="al-footer-content">
                <p class="al-text-center">
                    

                    <i class="fa fa-lg fa-code"></i>
                    <span>with</span>
                    <i class="fa fa-lg fa-heart"></i>
                    <span>by</span>
                    <a class="al-footer-link" href="{% url 'alpaca:about_us'%}">Darkatom & Sirikon</a>
                    
                    <span class="al-float-right al-footer-side-detail">
                        {% trans "Found a problem? Please," %}
                        <a class="al-footer-link" href="https://github.com/Darkatom/WarLlama/issues">{% trans "help us!" %}</a>
                    </span>

                    <span class="al-float-left al-footer-side-detail">
                        <a class="al-footer-link" href="{% url 'alpaca:terms_conditions'%}">
                            {% trans "Terms and Conditions" %}
                        </a>
                    </span>

                </p>
            </div>
        </div>
    </body>
</html>